# Generated by Django 5.0.1 on 2024-06-04 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="post",
            options={"ordering": ["-published_date"]},
        ),
    ]
