# Generated by Django 5.0.1 on 2024-06-04 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_accountsettings_profile"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="email",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="first_name",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="last_name",
        ),
    ]
