# Generated by Django 5.0.1 on 2024-06-05 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0005_product"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="image",
        ),
        migrations.AddField(
            model_name="product",
            name="slug",
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
